### ISSUE TITLE
Server terminates......

### ISSUE THREAD

**Issue by Suleman-Elahi** [rivyx/for-hue#1]
![image](https://user-images.githubusercontent.com/24384996/43068348-d2e394aa-8e87-11e8-97a5-16e718774bcf.png)

On Windows 10, it terminates the server right after I upload a PDF file.

**Comment by richnotwealthy** [comment]
Hi @Suleman-Elahi ! I'm glad you're finding my project here to be potentially useful. I made For Hue for a hackathon at my college and never intended it to be something I'd support through the years. You can try out the [demo on heroku](https://for-hue.herokuapp.com/) if you'd simply like to convert a pdf. Sadly, I'd advice against converting any large files (PDFs longer than ~5 pages). If I remember correctly, we never built out support for that.

If you'd still like to get a local development version of For Hue up on your machine, I'd recommend trying it out on Linux. I built this app on Ubuntu and the heroku server is a linux box. You can try utilizing the Linux Subsystem on Windows if you'd like to stick to windows, but honestly I'd recommend dual booting or installing a virtual machine (Vagrant Boxes are great!).
